// Central badge definitions. Used by GamificationContext for auto-awarding
// and by pages/components for rendering locked/earned states.

export const BADGE_DEFS = [
  { id: "streak_3",        label: "3 Day Streak",     icon: "flame",     color: "var(--orange)",
    desc: "Study 3 days in a row." },
  { id: "streak_7",        label: "7 Day Streak",     icon: "flame",     color: "var(--pink)",
    desc: "Study 7 days in a row. You are on fire." },
  { id: "streak_21",       label: "21 Day Streak",    icon: "flame",     color: "var(--red)",
    desc: "Study every day for 3 weeks. Legendary." },
  { id: "first_quiz",      label: "First Quiz",       icon: "trophy",   color: "var(--lime)",
    desc: "Answer your first micro quiz." },
  { id: "quiz_10",         label: "Quiz Champion",    icon: "trophy",   color: "var(--yellow)",
    desc: "Answer 10 micro quizzes." },
  { id: "quiz_perfect",    label: "Perfect Score",    icon: "star",     color: "var(--purple)",
    desc: "Get 3 quizzes correct first try in a row." },
  { id: "buddy",           label: "Study Buddy",      icon: "users",    color: "var(--pink)",
    desc: "Match with your first study buddy." },
  { id: "level_5",         label: "Level 5 Reached",  icon: "bolt",     color: "var(--purple)",
    desc: "Climb to Level 5." },
  { id: "xp_5000",         label: "5000 XP Club",     icon: "star",     color: "var(--blue)",
    desc: "Earn 5000 XP total." },
  { id: "first_course",    label: "First Course",     icon: "cap",      color: "var(--blue)",
    desc: "Start your first course." },
  { id: "course_complete", label: "Course Finisher",  icon: "checkCircle", color: "var(--lime)",
    desc: "Complete an entire course (all 8 chapters)." },
  { id: "vault",           label: "Resource Hunter",  icon: "download", color: "var(--purple)",
    desc: "Download 3 resources from the vault." },
  { id: "pomodoro_5",      label: "5 Focus Sessions", icon: "clock",    color: "var(--orange)",
    desc: "Complete 5 pomodoro focus sessions." },
  { id: "pomodoro_25",     label: "Focus Warrior",    icon: "mic",      color: "var(--purple)",
    desc: "Complete 25 pomodoro sessions." },
  { id: "focus_master",    label: "Focus Master",     icon: "shield",   color: "var(--yellow)",
    desc: "Log 500+ minutes of focused study." },
  { id: "daily_7",         label: "Week of Challenges", icon: "calendar", color: "var(--pink)",
    desc: "Complete 7 daily challenges." },
]
